name: CI

on:
  push:
    branches: [main, feat/ci-renovate-prettier]
  pull_request:
    branches: [main, feat/ci-renovate-prettier]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - run: npm install
      - run: npm run lint
      - run: npm run type-check